
PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS student;
CREATE TABLE student (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL UNIQUE, name VARCHAR (32), email VARCHAR (32), courses VARCHAR(300), user_type INTEGER);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
